language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/

after_success:
  - test ${TRAVIS_BRANCH} = master && export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - test ${TRAVIS_BRANCH} = master && export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - test ${TRAVIS_BRANCH} = master && ./gradlew deployProduction
