language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
env:
  matrix:
  - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_KEY=$AWS_SECRET_KEY
  global:
    secure: UI0brMsfIrVWoFLM3fY2AhV7ipknhZ3xeGow09mQHZ2AQmCHi93AGD37tL4atBBgYhd7eFg0Pw/1omFItKU4pPOd2GxvsIHWts11+7Bw3B0VrGuF6Te6EhT/s5noq826QAMzIJIFgOUNElD00u6jasGeNrD0xECTJupg4e2f0/m5qYcdvG3cz4bgX9OnpKzXonv0hHeD1ea7A+Kno6GSVco39A0LQMT5RM8X67gDaYHcDBIlYiC7tWdAWd1pwn7xvGR2Xgnp3PqOmRYIOUTpkDTsgHJggNq7uMjI3rZ9+F1ya0j3nn/RQ6XF3xSQXU8sLgitRt3oYy0gAoxawRkNnlspfNpZtko5/p6xJJaW913guxgfMnIs/I1Oy6Hyz57uxwSam8Mt/VNDZknZxlsPFiR/aXJ6JDZJ4O2onn1FQ0Ahdd5yudz1tIQGfa+1HuNAN+HdxlrTOta2b9m4LXK2YyplaYXfnO1TBTYW6RnYsiMOSil7RBOiTp/PmWgf2uwGlLntCjew88rpSHVbfVP0QloCVDbMSXCp90RSV6hjvegbQyHnQhLgeSCBrKhDh2o3gUafBokf30FOr5xPXu+r0FCil/Q4pFA0BMQt0Q3ZTumm+RtBY9YUIenjevRCjrsNDUp2XEYtS9/rtO4/PDKq7sFSFZgymPh3LQ5KKr9EPwQ=
after_success:
- test ${TRAVIS_BRANCH} = master && ./gradlew deployProduction
