language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/

after_success:
  - if [ ! -d "~/.aws" ]; then mkdir ~/.aws; fi
  - printf "[clippy-platform]\naws_access_key_id=%s\naws_secret_access_key=%s\n", $aws_access_key_id $aws_secret_access_key > ~/.aws/credentials
  - ./gradlew deployProduction
