language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/

after_success:
  - test ${TRAVIS_BRANCH} = master && ./gradlew -Daws.accessKeyId=$AWS_ACCESS_KEY_ID -Dws.secretKey=$AWS_SECRET_ACCESS_KEY deployProduction --stacktrace
