language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
env:
  global:
    secure: KJOmYvlkU5k8SN4Culv0g9uTp1P4HmdWZERJKgTYeEdDO48mRDW9rBMxIXbLjYCPZdaS91kDFYTrMHSXyN9Ha66NpwlILMRsyERWlmiQVQKvIa96xP1vPXOvZTHIGLBM8Wx6vCVL/q5wH03Zn752YCzWbu7srrPUN2xgYllRmKfTfB5xOyUQ333cHsmk+e4ewvR8B5cxSm/KezHgLyEpWVsBEjeGJpk5OrrjoDRNish3SDaM4LWaipx77ukAK1HLZLlkytmnzXaXtMDDynhjdOpXBRwfNYmMXIWqvVYKNrq6d0Z2eIR8zUE4qr07+DYdwy+AWO/qOe2Q63fYKbJ5gqyL6L6IXNBYSl6eH2BHcJB14kvG16eU4+ut/JP/9iXGLD+eh3nuzTk+VllLgLll+/UjuzhF5mJnDQd4TgI0vvEjMwDGI+yx2PA1rVh0BrUJo6Rq2IYIa7SUNDJ73F389fHll+OBu9Cg4VS6GqDWzBsjkQWwXowfZKXs2Wr8K+XhbEvgG9eIJKoSjE/GuPFMAoEXOxOcUEEQBGxyw42iWkzXL/FUKFz9xD1QmFEr/StBaFmRmAKflUgS3G1Kt9AXJ80BPawiEKw9QQRRStzqW6BsEcs8FBpw/hBH7WN3VkTesWYohTUTb+UtUjFkNtfPqj8DrUdDuygYQdw4EMJUnaM=
    secure: UI0brMsfIrVWoFLM3fY2AhV7ipknhZ3xeGow09mQHZ2AQmCHi93AGD37tL4atBBgYhd7eFg0Pw/1omFItKU4pPOd2GxvsIHWts11+7Bw3B0VrGuF6Te6EhT/s5noq826QAMzIJIFgOUNElD00u6jasGeNrD0xECTJupg4e2f0/m5qYcdvG3cz4bgX9OnpKzXonv0hHeD1ea7A+Kno6GSVco39A0LQMT5RM8X67gDaYHcDBIlYiC7tWdAWd1pwn7xvGR2Xgnp3PqOmRYIOUTpkDTsgHJggNq7uMjI3rZ9+F1ya0j3nn/RQ6XF3xSQXU8sLgitRt3oYy0gAoxawRkNnlspfNpZtko5/p6xJJaW913guxgfMnIs/I1Oy6Hyz57uxwSam8Mt/VNDZknZxlsPFiR/aXJ6JDZJ4O2onn1FQ0Ahdd5yudz1tIQGfa+1HuNAN+HdxlrTOta2b9m4LXK2YyplaYXfnO1TBTYW6RnYsiMOSil7RBOiTp/PmWgf2uwGlLntCjew88rpSHVbfVP0QloCVDbMSXCp90RSV6hjvegbQyHnQhLgeSCBrKhDh2o3gUafBokf30FOr5xPXu+r0FCil/Q4pFA0BMQt0Q3ZTumm+RtBY9YUIenjevRCjrsNDUp2XEYtS9/rtO4/PDKq7sFSFZgymPh3LQ5KKr9EPwQ=
after_success:
- test ${TRAVIS_BRANCH} = master && ./gradlew deployProduction
