language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/

after_success:
  - test ${TRAVIS_BRANCH} = master && ./gradlew -D"aws.accessKeyId"=$AWS_ACCESS_KEY_ID -D"aws.secretKey"=$AWS_SECRET_ACCESS_KEY deployProduction
