language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
env:
  - AWS_ACCESS_KEY_ID=foo AWS_SECRET_KEY=bar
after_success:
  - test ${TRAVIS_BRANCH} = master && ./gradlew deployProduction
